### ISSUE TITLE
error code 500 and error code langur

### ISSUE THREAD

**Issue by StormKiller1** [DeathMiner/RewardsGG-Farm#1]
i get these errors after while and when im using multiple accounts at once

**Comment by demaisj** [comment]
Hello,

The 500 error code is not a problem, it is coming from the shitty servers hosting the farm stats.
Also, I saw that 'Langur' error code but I don't know what error it does refer to. I'll do some research for a future update.

Hope this helps.

**Comment by demaisj** [comment]
So after studying the update of the get-tickets page, it seems that the 'Langur' error code means that 'we can't add tickets because you haven't waited enough'. This is not a serious bug here, but i know these popups are kind of annoying, even more if you don't know what is the error.

I'll fix this in the next update.

**Comment by StormKiller1** [comment]
thanks nice work by the way:)

**Comment by ItsEcholot** [comment]
If you want to, I could host your farm stats stuff on my dedicated server.

**Comment by demaisj** [comment]
Hi shock2provide,

I'm interested into your proposition. All I need is a Web Server supporting HTTPS and PHP5. Feel free to contact me by email : Jordan.Demaison @gmail.com

Thanks.
