### ISSUE TITLE
Not working in Safari 5.17 Windows Web Browser

### ISSUE THREAD

**Issue by ChinqeeTan** [DeathMiner/RewardsGG-Farm#20]
Hi DeathMiner! Im using Safari 5.17 Windows Web Browser with TamperMonkey Extension with rewardsGG-Farm script. However, it is not working. The Web Page still loads the original rewards.gg/get-tickets.com website. Does the script support safari browser? if so, which version of the safari web browser. Thank You!

**Comment by demaisj** [comment]
Hi,

This script has only been tested on chrome, as I don't use personally safari.
Can you send me a pic of the JavaScript console (Open the Development Tools > Console) so I can see if there is some errors I can fix ?
And please tell me what is your OS ?

Thanks!

**Comment by ChinqeeTan** [comment]
OS is windows 8.1. 
![1](https://cloud.githubusercontent.com/assets/20611730/17078805/f3d8ec6a-512f-11e6-9a48-5b428c099e53.PNG)
Im using safari for multi account farming. If it causes too much trouble then just decline this request. Thanks deathminer!

**Comment by demaisj** [comment]
Well I think the script just can't launch because Safari 5.17 is too old (2012) and since this version Apple has abandoned development of Safari on Windows (current version on MacOS is 10!).
All I can suggest to you is getting another browser, supporting latest modern technologies (ie chrome, edge, firefox).
If you don't want chrome, at least to run the script you can try Greasemonkey on firefox. If it doesn't work I can try to add a support for it.

**Comment by ChinqeeTan** [comment]
ok! thanks very much!

**Comment by demaisj** [comment]
I'm closing this issue for now as this can't be fixed because Safari is outdated.
If you have bugs about Greasemonkey or whatever please open a new issue.
