### ISSUE TITLE
Rewards v1.2.1b1 Update

### ISSUE THREAD

**Issue by ghost** [DeathMiner/RewardsGG-Farm#4]
Hello!,
I do not know what creates the problem, but occurred after update and change the ticket page.
Thanks for the great work.

**Comment by poorloading** [comment]
i have issues also, i hope he updates soon to fix ill the issues

**Comment by demaisj** [comment]
Hello,

They've changed the whole layout of the page, I have to start from scratch.
I'm rolling up next version (1.5) tomorrow.

**Comment by demaisj** [comment]
Hello, I've got news about the update:
I reworked the interface of the page (removed stream, ads & useless stuff). Here is what it looks like:
![image](https://cloud.githubusercontent.com/assets/2797696/13894664/e0c964c0-ed6a-11e5-9a37-878989e895c9.png)

**Comment by demaisj** [comment]
Hello fellow farmers,
I didn't have time to code the new update these last days. If you want you can try out the new update "as-is" by installing the script from the [/dev branch](https://github.com/DeathMiner/RewardsGG-Farm/blob/dev/rewardsgg-farm.user.js). By doing this you'll be able to test the script and communicate me bugs or suggestions!
Hope you'll like this update.

EDIT : My website is dead, that's why stats are showing a 403 error.

**Comment by demaisj** [comment]
Hi, I'm rolling out 1.5 update, this issue will be closed.
